---
Title:    Extended Laplace method and illustration
Goal: 	  Replicate results in "Removing collinearity while keeping interpretability"
Inputs:	  User settings (see options below)
          Data file - Laplace►_NLSY_data.csv
Outputs:  LaTex format - OLS/Laplace comparison table (2)				
		      LaTex format - Intermediate regression results table (3)
		      Orthogonalized data set - decor_data (data frame format)
Written:  robin m cross, 2.14.19
Release:  2.16.22 rc
--- 

Packages and libraries
```{r}

#Install if it's your first run
first_run <- 0
if (first_run) {
  
  # Clear Global Environment
  rm(list = ls())
  
  # Installation
  #install.packages("vtable")
  #install.packages("gtsummary")
  #install.packages("dataframes2xls")
  #install.packages("openxls")
  install.packages("stargazer")  
  install.packages("tidyverse")
  install.packages("dplyr")

    
} #End if first_run

# Libraries 
  #library(gtsummary)
  #library(vtable)

  #library(readxl)
  #library(dataframes2xls)
  #library(openxlsx)

  library(stargazer)
  library(tidyverse)
  library(dplyr)

```


Load data
```{r}
# Clear Global Environment
rm(list = ls())

#Load Data
run_data            <- read.delim('C:/data/laplace/R/Laplace_NLSY_data.csv')


```

User preferences
```{r}

# Set covaraiate retention threshold
# Drops covariates explained (R^2) greater than stated tolerance
# Set to 1.0 for no drops, 0.99 to drop when R^2 greater than 0.99
collin_tolerance		<- 0.99	

# Set results table print choice
# Table 2 - (save_intermediate=0) Results table compares OLS direct effects to Laplace total effects
# Table 3 - (save_intermediate=1) Intermediate regression results (all) - too large for some screen display
save_intermediate   <- 1

```

Order data, assign blocks
```{r}

# SAVE participant identifier data frame for later join with decor data and drop
identifiers <- select_at(run_data, vars("cpubid", "momid"))
run_data <- select(run_data, -ends_with("id"))
# Copy dep_var for merge with decor_data
dep_var <- select_at(run_data, vars("test_pcntl"))

# ORDER
col_order <- c("year2", "year3", "year4", "year5", "year6", "year7", "year8", "year9", "year10", "year11", "year12", "year13", "year14", "year15", "momrace1", "momrace2", "mage", "mom_grade", "momtest", "spouse_yn", "spouse_age", "spouse_grade", "csex2", "childage", "family_size", "fincome", "test_pcntl")
run_data <- run_data[, col_order]

# Create decor_data (to designate block names and run model)
# Group 0 - fixed effects
run_data <- rename_at(run_data, vars( contains("year") ), list( ~paste0(., "_sim0") ) )

# Group 1 - race effects
run_data <- rename_at(run_data, vars( contains("momrace") ), list( ~paste0(., "_sim1") ) )

# Group2 - mother characteristics
run_data <- rename_at(run_data, vars( mage:momtest), list( ~paste0(., "_seq2") ) )

# Group 3 - spousal characteristics
run_data <- rename_at(run_data, vars( contains("spouse_") ), list( ~paste0(., "_sim3") ) )

# Group4 - remaining covariates
run_data <- rename_at(run_data, vars( csex2:fincome), list( ~paste0(., "_seq4") ) )

# Name dep_var
run_data <- rename_at(run_data, vars(test_pcntl), list( ~paste0("dep_var") ) )

# Indicate initial and terminal block numbers, e.g., _sim0-_seq4 => startblock<-0, endblock<-4
startblock <- 0
endblock <- 4


```

Call laplace.R
```{r}

source("extended_laplace.R")

```


Run Ext. Laplace and print table 1 (OLS vs Ext. Laplace) or table 3 (intermediate regressions)
```{r}

# Center - all variables - creates a matrix
run_data <- sapply(run_data, function(x) scale(x, scale=FALSE))

# Convert back to data frame
run_data <- as.data.frame(run_data)

# Generate two blank lists (to hold compare and intermediate results)
int_list <- list()
comp_list <- list()

# Generate loop list
doublecount <- (endblock - startblock) * 2
nlist <- floor(seq(startblock, doublecount + 1) /2)
simlist <- c("_sim", "_seq")
nlist <- paste0(simlist, nlist)
rm(simlist, doublecount)

# Initial comp model - OLS direct effects
indvars <- select_at(run_data, vars(contains("_s")))
comp_list$model1=lm(run_data$dep_var ~ ., data=indvars)
rm(indvars)

# Gen empty decor_data data frame for orthogonalized covariates
decor_data <- data.frame()

# Initiate block and covariate counter variable
b <- 1
k <- 1
save_count <- 1

# Ext. Laplace loop
for (i in nlist) {
  
  ## List covariates in block
  c_list <- colnames(select_at(run_data, vars(contains(i))))
  c_group <- data.frame(select_at(run_data, vars(contains(i))))
  
  # Set group counters
  g <- 1
  G <- ncol(c_group)

  # Covariate block loop
  for (grp in g:G) {

    # Set try catch flag
    skip_to_next <- FALSE
    
    # Run OLS - if valid, continue, if invalid, move to next covariate
    tryCatch( model <- lm(c_group[,grp] ~ ., data=decor_data), error = function(e) { skip_to_next <<- TRUE}) #change to decor_data
    if(skip_to_next) { next } #End if skip
    
    # Check R^2 and drop model if above threshold
    r2 <- summary(model)$r.squared

    if(r2 > collin_tolerance) { 

      # Drop covariate and move to next covariate
      c_group = subset(c_group, select=-c(grp))
      
      next 
      
      } #End if r2
    
    # Add model to results list and proceed
    # Indicate which group to begin saving results - e.g., save_start = 1 begins saving group 1, save_start = 2 begins saving group 2...
    save_start <- 3
    # Save loop
    if (k >= save_start) {
      
      # Save model
      int_list[[save_count]] <- model
      
      # Advance save counter
      save_count = save_count + 1

      } #End if save to results list
    
    # Predict
    yhat <- predict(model, newdata = decor_data) #change to decor_data
    
    # Replace in c_group
    c_group[[grp]] <- c_group[[grp]] - yhat 
    
    # If sequential - add replacement to decor_data 
    target <- "_seq"
    if(grepl(target, i, fixed = TRUE)) {
      
      # Retrieve current variable 
      s_element <- c_list[grp]
      # Append variable into data
      decor_data <- append(decor_data, select_at(c_group, vars(contains(s_element))))
      
    } #End if sequential
    
    # Advance covariate counter
    k <- k + 1
    
  } #End loop over block

  # If block is simultaneous - add to decor_data 
  target <- "_sim"
  if(grepl(target, i, fixed = TRUE)) {
    
    # Populate decor_data if first block, add to it if a later block 
    if (b == 1) {
  
      # Populate
      decor_data <- c_group
    
      } else {
      
      # Add block 
      decor_data <- cbind(decor_data, c_group)
 
      } #End counter else
    
    } #End if simultaneous
  
  # Advance block counter
  b <- b + 1

  } #End Laplace loop

# Terminal comparison model - OLS direct vs Laplace total effects
model <- lm(run_data$dep_var ~ ., data=decor_data)
int_list[[save_count]] <- model
comp_list[[2]] <- model

```

PRINT TABLES AND SAVE DATA
```{r}

# Save data frames and clean up

# Convert identifiers and dependent variable to list to combine
id_list <- as.list(identifiers)
dep_list <- as.list(dep_var)

# Combine lists
decor_data <- c(id_list, decor_data, dep_list)

# Convert back to data frame
decor_data <- data.frame(decor_data)

# Clean up environment
rm(c_group, model, c_list, col_order, g, grp, G, i, b, nlist, r2, skip_to_next, yhat, dep_var)
rm(dep_list, id_list, identifiers)
rm(collin_tolerance, endblock, startblock, k, s_element, save_count, save_intermediate, save_start, target)


# Print comparison results

# List variables to omit
latex_omit <- c("Constant", "year2_sim0", "year3_sim0", "year4_sim0", "year5_sim0", "year6_sim0", "year7_sim0", "year8_sim0", "year9_sim0", "year10_sim0", "year11_sim0", "year12_sim0", "year13_sim0", "year14_sim0", "year15_sim0")

# Comparison results column header -- LaTex title
latex_cheaders <- c("OLS (DE)", "Ext. Laplace (TE)")

# Latex code Comparison Results (Model 1 is OLS (Direct Effects), Model 2 is Ext. Laplace (Total Effects))
stargazer(comp_list, title="Comparison Results",
dep.var.labels=c("Test Percentile "),
column.labels=c(latex_cheaders),
omit.stat=c("LL","aic","f","wald","adj.rsq", "ser"), 
omit = c(latex_omit), 
single.row=TRUE)


# Print intermediate results

# Intermediate results column header -- LaTex title
latex_iheaders <- c("mage", "mom_grade", "momtest", "spouseyn", "spouseage", "spousegrade", "csex2", "childage", "familysize", "fincome", "test_pcntl")

# Latex code Intermediate Results
stargazer(int_list, title="Intermediate Results",
dep.var.labels=c(""),
column.labels=c(latex_iheaders),
omit.stat=c("LL","aic","f","wald","adj.rsq", "ser"),
omit = c(latex_omit))

# Clean up
rm(latex_iheaders, latex_cheaders, latex_omit)


```













